name: my_recipes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # api packages
  dio_http_cache:
  dio:

  #GET
  get:
  get_storage:

  #LOG
  logger:

  #UTILS
  path_provider:
  shimmer: ^3.0.0
  cached_network_image:
  internet_connection_checker: ^1.0.0+1
  pull_to_refresh:
  flutter_staggered_animations:
  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
